function text = generateSessionSummary(summary)
%GENERATESESSIONSUMMARY English narrative for judges.

distancePart = sprintf("covered %.2f km", summary.DistanceKm);
if summary.DistanceSource == "stride_fallback"
    distancePart = distancePart + " from stride fallback";
end

text = sprintf([ ...
    "Solid session with a %.1f/100 Workout Quality Score and %.1f/100 Fatigue Index. " + ...
    "Detected sport: %s, led by %s for %.1f minutes. " + ...
    "The athlete %s, recorded about %d steps, and sustained %.1f active minutes. " + ...
    "Movement confidence is %.1f%% based on sensor regularity, classifier margin, and GPS availability. " + ...
    "%s. Estimated cadence was %.1f steps/min, calories were %.1f kcal, and active burn averaged %.2f kcal/min."], ...
    summary.WorkoutQualityScore, summary.FatigueIndex, summary.DetectedSport, ...
    summary.DominantActivity, summary.DominantActivityMinutes, distancePart, summary.StepCount, ...
    summary.ActiveMinutes, summary.ConfidenceIndex, summary.PeakFatigueLabel, ...
    summary.CadenceSpm, summary.EstimatedCalories, summary.ActiveCaloriesPerMinute);
end

